trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    pushd tritronFrontend
    npm install
    npm run build
  displayName: 'npm install and build'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'angular'
    targetPath: 'tritronFrontend/dist'